version: "3.7"

services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"